# data.py

music_library = [
    # --- CATEGORY 1: INDIAN CLASSICAL ---
    {"title": "Dádra", "artist": "Pt. Ravi Shankar", "genre": "Indian Classical", "mood": "Meditative", "tempo_bpm": 100, "duration_sec": 630, "language": "Instrumental"},
    {"title": "Máru-Bihág", "artist": "Pt. Ravi Shankar", "genre": "Indian Classical", "mood": "Calm", "tempo_bpm": 110, "duration_sec": 704, "language": "Instrumental"},
    {"title": "Bhimpalási", "artist": "Pt. Ravi Shankar", "genre": "Indian Classical", "mood": "Calm", "tempo_bpm": 120, "duration_sec": 733, "language": "Instrumental"},
    {"title": "Raga Bhairavi", "artist": "Bismillah Khan", "genre": "Indian Classical", "mood": "Spiritual", "tempo_bpm": 110, "duration_sec": 563, "language": "Instrumental"},
    {"title": "Bhopali", "artist": "Bismillah Khan", "genre": "Indian Classical", "mood": "Calm", "tempo_bpm": 105, "duration_sec": 1009, "language": "Instrumental"},
    {"title": "Dhun", "artist": "Bismillah Khan", "genre": "Indian Classical", "mood": "Meditative", "tempo_bpm": 95, "duration_sec": 569, "language": "Instrumental"},
    {"title": "Kajari", "artist": "Bismillah Khan", "genre": "Indian Classical", "mood": "Meditative", "tempo_bpm": 90, "duration_sec": 300, "language": "Instrumental"},
    {"title": "Madhmas", "artist": "Bismillah Khan", "genre": "Indian Classical", "mood": "Energetic", "tempo_bpm": 100, "duration_sec": 761, "language": "Instrumental"},
    {"title": "Vatapi Ganapatim", "artist": "M.S. Subbulakshmi", "genre": "Carnatic Classical", "mood": "Devotional", "tempo_bpm": 83, "duration_sec": 427, "language": "Sanskrit"},
    {"title": "Kanakadharastavam", "artist": "M.S. Subbulakshmi", "genre": "Carnatic Classical", "mood": "Devotional", "tempo_bpm": 85, "duration_sec": 530, "language": "Sanskrit"},
    {"title": "Bhaja Govindham", "artist": "M.S. Subbulakshmi", "genre": "Carnatic Classical", "mood": "Devotional", "tempo_bpm": 80, "duration_sec": 661, "language": "Sanskrit"},
    {"title": "Jo Aghyuthananda", "artist": "M.S. Subbulakshmi", "genre": "Carnatic Classical", "mood": "Calm", "tempo_bpm": 75, "duration_sec": 370, "language": "Telugu"},
    {"title": "Kurai Onrum Illai", "artist": "M.S. Subbulakshmi", "genre": "Carnatic Classical", "mood": "Meditative", "tempo_bpm": 82, "duration_sec": 286, "language": "Tamil"},
    {"title": "Brahma Kadigina", "artist": "M.S. Subbulakshmi", "genre": "Carnatic Classical", "mood": "Devotional", "tempo_bpm": 88, "duration_sec": 269, "language": "Telugu"},
    {"title": "Nagumomu", "artist": "M.S. Subbulakshmi", "genre": "Carnatic Classical", "mood": "Calm", "tempo_bpm": 90, "duration_sec": 400, "language": "Telugu"},
    {"title": "Ud Re Ud Bihangam", "artist": "Shubha Mudgal", "genre": "Hindustani Classical", "mood": "Spiritual", "tempo_bpm": 85, "duration_sec": 240, "language": "Hindi"},
    {"title": "Main To Piya Se", "artist": "Nusrat Fateh Ali Khan", "genre": "Classical Sufi", "mood": "Energetic", "tempo_bpm": 95, "duration_sec": 409, "language": "Urdu"},
    {"title": "Tere Ishq Nachaya", "artist": "Abida Parveen", "genre": "Classical Sufi", "mood": "Energetic", "tempo_bpm": 110, "duration_sec": 284, "language": "Punjabi"},
    {"title": "Jeeni Bheeni Chadariya", "artist": "Gundecha Brothers", "genre": "Hindustani Classical", "mood": "Meditative", "tempo_bpm": 70, "duration_sec": 285, "language": "Hindi"},
    
    # --- CATEGORY 2: DEVOTIONAL ---
    {"title": "Kun Faya Kun", "artist": "A.R. Rahman", "genre": "Sufi", "mood": "Spiritual", "tempo_bpm": 127, "duration_sec": 470, "language": "Hindi/Urdu"},
    {"title": "Achyutam Keshavam", "artist": "Vikram Hazra", "genre": "Devotional", "mood": "Calm", "tempo_bpm": 93, "duration_sec": 351, "language": "Sanskrit"},
    {"title": "Mauli Mauli", "artist": "Ajay-Atul", "genre": "Devotional", "mood": "Energetic", "tempo_bpm": 105, "duration_sec": 250, "language": "Marathi"},
    {"title": "Tu Sukhkarta Tu Dukh Harta", "artist": "Vasantrao Deshpande", "genre": "Devotional", "mood": "Spiritual", "tempo_bpm": 83, "duration_sec": 240, "language": "Marathi"},
    {"title": "Guru Mantra Brahma Vishnu Shiv", "artist": "Vishal Khera", "genre": "Devotional", "mood": "Meditative", "tempo_bpm": 83, "duration_sec": 300, "language": "Sanskrit"},
    {"title": "Hanuman Chalisa", "artist": "Narendra Chanchal", "genre": "Devotional", "mood": "Energetic", "tempo_bpm": 83, "duration_sec": 400, "language": "Awadhi/Hindi"},
    {"title": "Vaishnav Jan To", "artist": "Palak Muchhal", "genre": "Devotional", "mood": "Calm", "tempo_bpm": 83, "duration_sec": 250, "language": "Gujarati"},
    {"title": "Sri Hanuman Kavacham", "artist": "Puttur Narasimha Nayak", "genre": "Devotional", "mood": "Spiritual", "tempo_bpm": 82, "duration_sec": 320, "language": "Sanskrit"},
    {"title": "Durgadevi Kavacham", "artist": "Priya Sisters", "genre": "Devotional", "mood": "Spiritual", "tempo_bpm": 82, "duration_sec": 450, "language": "Sanskrit"},
    {"title": "Sarvamangala Mangalye", "artist": "Asha Bhosle", "genre": "Devotional", "mood": "Calm", "tempo_bpm": 82, "duration_sec": 300, "language": "Sanskrit"},
    {"title": "Pundalik Varde", "artist": "Abhanga Repost", "genre": "Devotional", "mood": "Energetic", "tempo_bpm": 82, "duration_sec": 210, "language": "Marathi"},
    {"title": "Shri Krishna Govind Hare Murari", "artist": "Mame Khan", "genre": "Devotional", "mood": "Spiritual", "tempo_bpm": 84, "duration_sec": 340, "language": "Hindi"},
    {"title": "Raghu Pati Raghav Raja Ram", "artist": "Rakesh Kala", "genre": "Devotional", "mood": "Calm", "tempo_bpm": 82, "duration_sec": 280, "language": "Hindi"},
    {"title": "Jagdambike Jai Jai", "artist": "Hari Om Sharan", "genre": "Devotional", "mood": "Spiritual", "tempo_bpm": 90, "duration_sec": 732, "language": "Hindi"},
    {"title": "Pitu Matu Sahayak", "artist": "Mukesh", "genre": "Devotional", "mood": "Calm", "tempo_bpm": 85, "duration_sec": 185, "language": "Hindi"},
    {"title": "O Shirdi Ke Sai Baba", "artist": "Mukesh", "genre": "Devotional", "mood": "Spiritual", "tempo_bpm": 88, "duration_sec": 252, "language": "Hindi"},
    {"title": "Sri Krishna Ashtaga", "artist": "P.B. Sreenivas", "genre": "Devotional", "mood": "Meditative", "tempo_bpm": 80, "duration_sec": 196, "language": "Sanskrit"},
    {"title": "Sri Mahalakshmi Ashtakaam", "artist": "P.B. Sreenivas", "genre": "Devotional", "mood": "Spiritual", "tempo_bpm": 85, "duration_sec": 244, "language": "Sanskrit"},
    {"title": "Navratricha San Sonyacha", "artist": "Sumeet Music", "genre": "Devotional", "mood": "Energetic", "tempo_bpm": 110, "duration_sec": 364, "language": "Marathi"},
    {"title": "Bhavanichi Talwar", "artist": "Sumeet Music", "genre": "Devotional", "mood": "Energetic", "tempo_bpm": 115, "duration_sec": 305, "language": "Marathi"},
    
    # --- CATEGORY 3: BOLLYWOOD & PAN-INDIAN CINEMA ---
    {"title": "Kesariya", "artist": "Arijit Singh", "genre": "Bollywood", "mood": "Romantic", "tempo_bpm": 90, "duration_sec": 269, "language": "Hindi"},
    {"title": "Sairat Zaala Ji", "artist": "Ajay-Atul", "genre": "Marathi Cinema", "mood": "Romantic", "tempo_bpm": 85, "duration_sec": 377, "language": "Marathi"},
    {"title": "Zingaat", "artist": "Ajay-Atul", "genre": "Marathi Cinema", "mood": "Energetic", "tempo_bpm": 128, "duration_sec": 226, "language": "Marathi"},
    {"title": "Ponni Nadhi", "artist": "A.R. Rahman", "genre": "Tamil Cinema", "mood": "Energetic", "tempo_bpm": 110, "duration_sec": 290, "language": "Tamil"},
    {"title": "Ra Ra Rakkamma", "artist": "B. Ajaneesh Loknath", "genre": "Kannada Cinema", "mood": "Energetic", "tempo_bpm": 115, "duration_sec": 218, "language": "Kannada"},
    {"title": "Malare", "artist": "Vijay Yesudas", "genre": "Malayalam Cinema", "mood": "Romantic", "tempo_bpm": 75, "duration_sec": 315, "language": "Malayalam"},
    {"title": "Belageddu", "artist": "Vijay Prakash", "genre": "Kannada Cinema", "mood": "Joyful", "tempo_bpm": 100, "duration_sec": 217, "language": "Kannada"},
    {"title": "Leke Prabhu Ka Naam", "artist": "Arijit Singh", "genre": "Bollywood", "mood": "Energetic", "tempo_bpm": 120, "duration_sec": 213, "language": "Hindi"},
    {"title": "Nashe Si Chadh Gayi", "artist": "Arijit Singh", "genre": "Bollywood", "mood": "Energetic", "tempo_bpm": 125, "duration_sec": 236, "language": "Hindi"},
    {"title": "Jhoome Jo Pathaan", "artist": "Arijit Singh", "genre": "Bollywood", "mood": "Energetic", "tempo_bpm": 118, "duration_sec": 207, "language": "Hindi"},
    {"title": "Dhoom Machale", "artist": "Sunidhi Chauhan", "genre": "Bollywood", "mood": "Energetic", "tempo_bpm": 120, "duration_sec": 369, "language": "Hindi"},
    {"title": "Swag Se Swagat", "artist": "Vishal Dadlani", "genre": "Bollywood", "mood": "Energetic", "tempo_bpm": 115, "duration_sec": 232, "language": "Hindi"},
    {"title": "Besharam Rang", "artist": "Shilpa Rao", "genre": "Bollywood", "mood": "Energetic", "tempo_bpm": 112, "duration_sec": 256, "language": "Hindi"},
    {"title": "Ghungroo", "artist": "Arijit Singh", "genre": "Bollywood", "mood": "Joyful", "tempo_bpm": 118, "duration_sec": 298, "language": "Hindi"},
    {"title": "Kajra Re", "artist": "Alisha Chinai", "genre": "Bollywood", "mood": "Energetic", "tempo_bpm": 105, "duration_sec": 478, "language": "Hindi"},
    {"title": "Sariyaagi", "artist": "Armaan Malik", "genre": "Kannada Cinema", "mood": "Romantic", "tempo_bpm": 100, "duration_sec": 262, "language": "Kannada"},
    {"title": "Summane", "artist": "Shreya Ghoshal", "genre": "Kannada Cinema", "mood": "Romantic", "tempo_bpm": 95, "duration_sec": 288, "language": "Kannada"},
    {"title": "Neene Neene", "artist": "Kunal Ganjawala", "genre": "Kannada Cinema", "mood": "Joyful", "tempo_bpm": 110, "duration_sec": 271, "language": "Kannada"},
    {"title": "O Preetiye", "artist": "S.P. Balasubrahmanyam", "genre": "Kannada Cinema", "mood": "Romantic", "tempo_bpm": 90, "duration_sec": 314, "language": "Kannada"},
    {"title": "Nanniralu", "artist": "Kunal Ganjawala", "genre": "Kannada Cinema", "mood": "Romantic", "tempo_bpm": 95, "duration_sec": 295, "language": "Kannada"},
    
    # --- CATEGORY 4: GLOBAL POP & WESTERN ---
    {"title": "Blinding Lights", "artist": "The Weeknd", "genre": "Synth-pop", "mood": "Energetic", "tempo_bpm": 171, "duration_sec": 200, "language": "English"},
    {"title": "Bohemian Rhapsody", "artist": "Queen", "genre": "Rock Opera", "mood": "Dramatic", "tempo_bpm": 144, "duration_sec": 355, "language": "English"},
    {"title": "Fly Me To The Moon", "artist": "Frank Sinatra", "genre": "Jazz", "mood": "Calm", "tempo_bpm": 120, "duration_sec": 147, "language": "English"},
    {"title": "Despacito", "artist": "Luis Fonsi", "genre": "Latin Pop", "mood": "Energetic", "tempo_bpm": 88, "duration_sec": 227, "language": "Spanish"},
    {"title": "Enjoy Enjaami", "artist": "Dhee ft. Arivu", "genre": "Pop", "mood": "Energetic", "tempo_bpm": 95, "duration_sec": 306, "language": "Tamil"},
    {"title": "Death Bed (Coffee for Your Head)", "artist": "Powfu", "genre": "Hip Hop", "mood": "Melancholic", "tempo_bpm": 144, "duration_sec": 173, "language": "English"},
    {"title": "Die With A Smile", "artist": "Lady GaGa & Bruno Mars", "genre": "Pop", "mood": "Romantic", "tempo_bpm": 109, "duration_sec": 251, "language": "English"},
    {"title": "Careless Whisper", "artist": "George Michael", "genre": "Pop", "mood": "Romantic", "tempo_bpm": 110, "duration_sec": 300, "language": "English"},
    {"title": "Closer", "artist": "The Chainsmokers", "genre": "Pop", "mood": "Energetic", "tempo_bpm": 111, "duration_sec": 244, "language": "English"},
    {"title": "Die For You", "artist": "The Weeknd", "genre": "Pop", "mood": "Romantic", "tempo_bpm": 112, "duration_sec": 260, "language": "English"},
    {"title": "Wake Me Up!", "artist": "Avicii", "genre": "EDM", "mood": "Energetic", "tempo_bpm": 124, "duration_sec": 247, "language": "English"},
    {"title": "Bad Habits", "artist": "Ed Sheeran", "genre": "Pop", "mood": "Energetic", "tempo_bpm": 126, "duration_sec": 231, "language": "English"},
    {"title": "Cold Heart", "artist": "Elton John & Dua Lipa", "genre": "Pop", "mood": "Joyful", "tempo_bpm": 116, "duration_sec": 202, "language": "English"},
    {"title": "Poker Face", "artist": "Lady GaGa", "genre": "Pop", "mood": "Energetic", "tempo_bpm": 119, "duration_sec": 237, "language": "English"},
    {"title": "Like A Prayer", "artist": "Madonna", "genre": "Pop", "mood": "Energetic", "tempo_bpm": 111, "duration_sec": 341, "language": "English"},
    {"title": "Tik Tok", "artist": "Ke$ha", "genre": "Pop", "mood": "Energetic", "tempo_bpm": 120, "duration_sec": 200, "language": "English"},
    {"title": "Billie Jean", "artist": "Michael Jackson", "genre": "Pop", "mood": "Energetic", "tempo_bpm": 117, "duration_sec": 294, "language": "English"},
    {"title": "The One That Got Away", "artist": "Katy Perry", "genre": "Pop", "mood": "Melancholic", "tempo_bpm": 134, "duration_sec": 227, "language": "English"},
    {"title": "Lush Life", "artist": "Zara Larsson", "genre": "Pop", "mood": "Joyful", "tempo_bpm": 98, "duration_sec": 201, "language": "English"},
    {"title": "Beauty and a Beat", "artist": "Justin Bieber", "genre": "Pop", "mood": "Energetic", "tempo_bpm": 128, "duration_sec": 228, "language": "English"},
    
    # --- CATEGORY 5: LO-FI & SLOWED/REVERB ---
    {"title": "Tu Kuja Man Kuja (Slowed+Reverb)", "artist": "Shiraz Uppal", "genre": "Lo-fi", "mood": "Calm", "tempo_bpm": 80, "duration_sec": 508, "language": "Urdu"},
    {"title": "Agar Tum Saath Ho Lofi Flip", "artist": "Alka Yagnik & Arijit Singh", "genre": "Lo-fi", "mood": "Calm", "tempo_bpm": 61, "duration_sec": 287, "language": "Hindi"},
    {"title": "Pasoori (Lofi)", "artist": "Ali Sethi & Shae Gill", "genre": "Lo-fi", "mood": "Melancholic", "tempo_bpm": 85, "duration_sec": 249, "language": "Punjabi/Urdu"},
    {"title": "Snowman (Lofi Soundscape)", "artist": "Sia", "genre": "Lo-fi", "mood": "Calm", "tempo_bpm": 105, "duration_sec": 166, "language": "English"},
    {"title": "Tujhe Sochta Hoon (Lofi Flip)", "artist": "KK", "genre": "Lo-fi", "mood": "Romantic", "tempo_bpm": 75, "duration_sec": 250, "language": "Hindi"},
    {"title": "Raataan Chill Mix", "artist": "Jubin Nautiyal", "genre": "Lo-fi", "mood": "Calm", "tempo_bpm": 80, "duration_sec": 230, "language": "Hindi"},
    {"title": "Tera Zikr (Lofi Flip)", "artist": "Darshan Raval", "genre": "Lo-fi", "mood": "Romantic", "tempo_bpm": 85, "duration_sec": 215, "language": "Hindi"},
    {"title": "Soniyo (Lofi Flip)", "artist": "Sonu Nigam", "genre": "Lo-fi", "mood": "Romantic", "tempo_bpm": 80, "duration_sec": 260, "language": "Hindi"},
    {"title": "Mitwa (Lofi Flip)", "artist": "Shankar Mahadevan", "genre": "Lo-fi", "mood": "Calm", "tempo_bpm": 90, "duration_sec": 310, "language": "Hindi"},
    {"title": "Kal Ho Naa Ho (Lofi Flip)", "artist": "Shankar-Ehsaan-Loy", "genre": "Lo-fi", "mood": "Melancholic", "tempo_bpm": 85, "duration_sec": 320, "language": "Hindi"},
    {"title": "O Sanam (DJ NYK Lofi Remix)", "artist": "Lucky Ali", "genre": "Lo-fi", "mood": "Calm", "tempo_bpm": 90, "duration_sec": 255, "language": "Hindi"},
    {"title": "Tu Aashiqui Hai (Lofi Remix)", "artist": "KK", "genre": "Lo-fi", "mood": "Romantic", "tempo_bpm": 88, "duration_sec": 245, "language": "Hindi"},
    {"title": "Baha Le Jaa (NEMO LoFi Flip)", "artist": "Arjun Kanungo", "genre": "Lo-fi", "mood": "Calm", "tempo_bpm": 70, "duration_sec": 140, "language": "Hindi"},
    {"title": "Sajde (LoFi Mix)", "artist": "Arijit Singh", "genre": "Lo-fi", "mood": "Romantic", "tempo_bpm": 82, "duration_sec": 270, "language": "Hindi"},
    {"title": "Samjhawan (Lofi Flip)", "artist": "Arijit Singh", "genre": "Lo-fi", "mood": "Melancholic", "tempo_bpm": 78, "duration_sec": 265, "language": "Hindi"},
    {"title": "Kabhii Tumhhe (Lofi Flip)", "artist": "Darshan Raval", "genre": "Lo-fi", "mood": "Melancholic", "tempo_bpm": 80, "duration_sec": 240, "language": "Hindi"},
    {"title": "Dil Se Re (LO-FI Remix)", "artist": "A. R. Rahman", "genre": "Lo-fi", "mood": "Calm", "tempo_bpm": 85, "duration_sec": 300, "language": "Hindi"},
    {"title": "Mera Dil Bhi Kitna Pagal Hai (Lo Fi Remix)", "artist": "Stebin Ben", "genre": "Lo-fi", "mood": "Romantic", "tempo_bpm": 80, "duration_sec": 280, "language": "Hindi"},
    {"title": "Kaali Kaali Aankhen (Lo Fi Remix)", "artist": "Kumar Sanu", "genre": "Lo-fi", "mood": "Calm", "tempo_bpm": 95, "duration_sec": 290, "language": "Hindi"},
    {"title": "Ek Din Aap Yun (Lo-Fi Remix)", "artist": "Kumar Sanu", "genre": "Lo-fi", "mood": "Calm", "tempo_bpm": 82, "duration_sec": 250, "language": "Hindi"}
]
